# config Person using YAML
person:
  name: zhao
  age: 1200
  flag: false
  birth: 2020/02/02
  map: {k1: v1,k2: v2}
  list:
    - coding
    - lanmei
  dog:
    name: wangcai
    age: 3
server:
  port: 8084
